export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const GET_USER_MENU = "GET_USER_MENU";
export const GET_USER_MENU_ERROR = "GET_USER_MENU_ERROR";
export const POST_USER_ORDER = "POST_USER_ORDER";
export const POST_USER_ORDER_ERROR = "POST_USER_ORDER_ERROR";
